.TH "listeurFic" 3 "Thu Dec 19 2013" "ACSIGroupe35Curling" \" -*- nroff -*-
.ad l
.nh
.SH NAME
listeurFic \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <listeurFic\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBlister\fP (std::string nomDossier)"
.br
.RI "\fIliste les fichiers d'un dossier \fP"
.ti -1c
.RI "std::string * \fBgetListe\fP ()"
.br
.RI "\fIretourne les noms/chemins fichiers listés \fP"
.ti -1c
.RI "void \fBlister\fP (std::string nomDossier)"
.br
.RI "\fIliste les fichiers d'un dossier \fP"
.ti -1c
.RI "std::string * \fBgetListe\fP ()"
.br
.RI "\fIretourne les noms/chemins fichiers listés \fP"
.in -1c
.SH "Detailed Description"
.PP 
classe \&.\&.\&. 
.SH "Member Function Documentation"
.PP 
.SS "string * listeurFic::getListe ()"

.PP
retourne les noms/chemins fichiers listés 
.PP
\fBReturns:\fP
.RS 4
le tableau des nom/chemins des fichiers listés
.RE
.PP
Fonction qui retourne la liste des fichiers 
.SS "std::string* listeurFic::getListe ()"

.PP
retourne les noms/chemins fichiers listés 
.PP
\fBReturns:\fP
.RS 4
le tableau des nom/chemins des fichiers listés
.RE
.PP
Fonction qui retourne la liste des fichiers 
.SS "void listeurFic::lister (std::stringnomDossier)"

.PP
liste les fichiers d'un dossier 
.PP
\fBParameters:\fP
.RS 4
\fInomDossier\fP : le fichier a lire
.RE
.PP
Méthode qui liste les fichiers dans un dossier dont le nom est donné en paramètre (nomDossier) 
.SS "void listeurFic::lister (std::stringnomDossier)"

.PP
liste les fichiers d'un dossier 
.PP
\fBParameters:\fP
.RS 4
\fInomDossier\fP : le fichier a lire
.RE
.PP
Méthode qui liste les fichiers dans un dossier dont le nom est donné en paramètre (nomDossier) 

.SH "Author"
.PP 
Generated automatically by Doxygen for ACSIGroupe35Curling from the source code\&.
