.TH "/home/toast/ACSIGroupe3Curling/ACSIGroupe35Curling/src/Curling/parseurFic.h" 3 "Tue Dec 24 2013" "ACSIGroupe35Curling" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/toast/ACSIGroupe3Curling/ACSIGroupe35Curling/src/Curling/parseurFic.h \- 
.PP
Parseur de fichier\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <QtCore>\fP
.br
\fC#include 'urlvalidator\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBparseurFic\fP"
.br
.RI "\fIclasse représentant le parseur de fichier \fP"
.in -1c
.SH "Detailed Description"
.PP 
Parseur de fichier\&. 


.PP
\fBAuthor:\fP
.RS 4
E\&.Tosi 
.RE
.PP
\fBDate:\fP
.RS 4
11\&.12\&.2013
.RE
.PP
classe gérant la lecture depuis un fichier à la recherche d'url stockées dans TODO 
.SH "Author"
.PP 
Generated automatically by Doxygen for ACSIGroupe35Curling from the source code\&.
