.TH "parseurFic" 3 "Thu Dec 12 2013" "ACSIGroupe35Curling" \" -*- nroff -*-
.ad l
.nh
.SH NAME
parseurFic \- 
.PP
classe représentant le parseur de fichier  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <parseurFic\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBlireFic\fP (std::string nomFic)"
.br
.RI "\fIlis le fichier et y prend les url \fP"
.ti -1c
.RI "void \fBgetUrls\fP ()"
.br
.RI "\fIretourne les url lues \fP"
.in -1c
.SH "Detailed Description"
.PP 
classe représentant le parseur de fichier 

classe gérant la lecture depuis un fichier à la recherche d'url stockées dans TODO 
.SH "Member Function Documentation"
.PP 
.SS "void parseurFic::getUrls ()"

.PP
retourne les url lues 
.PP
\fBReturns:\fP
.RS 4
le tableau d'url
.RE
.PP
Fonction qui retourne les url lues dans un fichier au préalable 
.SS "void parseurFic::lireFic (std::stringnomFic)"

.PP
lis le fichier et y prend les url 
.PP
\fBParameters:\fP
.RS 4
\fInomFic\fP : le fichier a lire
.RE
.PP
Méthode qui lis le fichier passé en paramètre et accumule les url qu'il y trouve 

.SH "Author"
.PP 
Generated automatically by Doxygen for ACSIGroupe35Curling from the source code\&.
