.TH "/home/toast/ACSIGroupe3Curling/ACSIGroupe35Curling/src/Curling/urlvalidator.h" 3 "Thu Jan 16 2014" "ACSIGroupe35Curling" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/toast/ACSIGroupe3Curling/ACSIGroupe35Curling/src/Curling/urlvalidator.h \- 
.PP
Valideur d'URL\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <QRegExp>\fP
.br
\fC#include <QtCore>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBurlValidator\fP"
.br
.RI "\fIclasse représentant le valideur de fichier d'URL \fP"
.in -1c
.SH "Detailed Description"
.PP 
Valideur d'URL\&. 


.PP
\fBAuthor:\fP
.RS 4
E\&.Tosi 
.RE
.PP
\fBDate:\fP
.RS 4
20\&.12\&.2013
.RE
.PP
classe gérant les tests appliqués à une URL 
.SH "Author"
.PP 
Generated automatically by Doxygen for ACSIGroupe35Curling from the source code\&.
