.TH "Vue" 3 "Tue Dec 24 2013" "ACSIGroupe35Curling" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Vue \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits QMainWindow\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBclearText\fP ()"
.br
.ti -1c
.RI "void \fBaddLigne\fP (QString ligne)"
.br
.ti -1c
.RI "void \fBsetCurProgression\fP (int progress)"
.br
.ti -1c
.RI "void \fBsetMaxProgression\fP (int maximum)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVue\fP (QWidget *parent=0)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for ACSIGroupe35Curling from the source code\&.
