.TH "/home/toast/ACSIGroupe3Curling/ACSIGroupe35Curling/src/Curling/vue.h" 3 "Thu Jan 16 2014" "ACSIGroupe35Curling" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/toast/ACSIGroupe3Curling/ACSIGroupe35Curling/src/Curling/vue.h \- 
.PP
vue principale  

.SH SYNOPSIS
.br
.PP
\fC#include <QtCore>\fP
.br
\fC#include <QtGui/QtGui>\fP
.br
\fC#include 'controlvue\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBVue\fP"
.br
.RI "\fIclasse représentant la vue principale \fP"
.in -1c
.SH "Detailed Description"
.PP 
vue principale 


.PP
\fBAuthor:\fP
.RS 4
E\&.Tosi 
.RE
.PP
\fBDate:\fP
.RS 4
24\&.12\&.2013
.RE
.PP
classe gérant la vue principale 
.SH "Author"
.PP 
Generated automatically by Doxygen for ACSIGroupe35Curling from the source code\&.
